name: PHPCS checks

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      - uses: sshnaidm/gpt-code-review-action
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          # Post comment with text even if step failed
          post-if-error: 'true'
